# Generated by Django 4.2.23 on 2025-08-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
    ]
